CREATE DATABASE CLEANHOME;
USE CLEANHOME;

CREATE TABLE USER(
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ENABLED BIT(1),
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE ROL(
    ID INT NOT NULL AUTO_INCREMENT,
    AUTHORITY VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    INDEX USERNM (USERNAME),
        FOREIGN KEY (USERNAME)
            REFERENCES USER(USERNAME)
            ON DELETE CASCADE,
        PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    CELLPHONE VARCHAR(10) NOT NULL,
    BIRTHDAY TIMESTAMP NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    INDEX USERNM (USERNAME),
        FOREIGN KEY (USERNAME)
            REFERENCES USER(USERNAME)
            ON DELETE CASCADE,
        PRIMARY KEY (ID)
);