CREATE DATABASE CLEANHOME;
USE CLEANHOME;


CREATE TABLE USER(
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ENABLED BIT(1),
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE ROL(
    ID INT NOT NULL AUTO_INCREMENT,
    AUTHORITY VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    INDEX USERNM (USERNAME),
        FOREIGN KEY (USERNAME)
            REFERENCES USER(USERNAME)
            ON DELETE CASCADE,
        PRIMARY KEY (ID)
);

