CREATE DATABASE CLEANHOME;
USE CLEANHOME;

CREATE TABLE USER(
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ENABLED BIT(1),
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE ROL(
    ID INT NOT NULL AUTO_INCREMENT,
    AUTHORITY VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    INDEX USERNM (USERNAME),
        FOREIGN KEY (USERNAME)
            REFERENCES USER(USERNAME)
            ON DELETE CASCADE,
        PRIMARY KEY (ID)
);

CREATE TABLE USUARIO(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    CELLPHONE VARCHAR(10) NOT NULL,
    BIRTHDAY TIMESTAMP NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    INDEX USERNM (USERNAME),
        FOREIGN KEY (USERNAME)
            REFERENCES USER(USERNAME)
            ON DELETE CASCADE,
        PRIMARY KEY (ID)
);

CREATE TABLE SERVICIO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(150) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TIPO_PROPIEDAD(
    ID INT NOT NULL AUTO_INCREMENT,
    TIPO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
)

CREATE TABLE ESTADO(
    ID INT NOT NULL AUTO_INCREMENT,
    ESTADO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
)

CREATE TABLE PUBLICACION(
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PAGO_OFRECIDO FLOAT(7,2) NOT NULL,
    ID_SERVICIO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    INDEX IDUSR (ID_USUARIO),
    INDEX IDSRV (ID_SERVICIO),
        FOREIGN KEY (ID_USUARIO)
            REFERENCES USUARIO(ID)
            ON DELETE CASCADE,
        FOREIGN KEY (ID_SERVICIO)
            REFERENCES SERVICIO(ID)
            ON DELETE CASCADE,
        PRIMARY KEY (ID));

CREATE TABLE PROPIEDAD(
    ID INT NOT NULL AUTO_INCREMENT,
    FOTO VARCHAR(100) NOT NULL,
    TITULO VARCHAR(30) NOT NULL,
    CALLE VARCHAR(30) NOT NULL,
    NUMERO_EXTERIOR VARCHAR(10) NOT NULL,
    CODIGO_POSTAL VARCHAR(10) NOT NULL,
    COLONIA VARCHAR(30) NOT NULL,
    REFERENCIAS VARCHAR(50) NOT NULL,
    COMPROBANTE VARCHAR(100) NOT NULL,
    ESTATUS VARCHAR(30) NOT NULL,
    ID_ESTADO INT NOT NULL,
    ID_TIPO_PROPIEDAD INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    INDEX IDEST (ID_ESTADO),
    INDEX IDUSR (ID_USUARIO),
    INDEX IDTPR (ID_TIPO_PROPIEDAD),
        FOREIGN KEY (ID_ESTADO)
            REFERENCES ESTADO(ID)
            ON DELETE CASCADE,
        FOREIGN KEY (ID_USUARIO)
            REFERENCES USUARIO(ID)
            ON DELETE CASCADE,
        FOREIGN KEY (ID_TIPO_PROPIEDAD)
            REFERENCES TIPO_PROPIEDAD(ID)
            ON DELETE CASCADE,
        PRIMARY KEY (ID)
);
